# Target browser: chrome, firefox, edge
browser=chrome

# Application Base URL
url=https://timeflow.setoo.in

# Headless mode: false for visual execution, true for headless
headless=false

# Explicit wait timeout in seconds
timeout=15

# Maximize browser on startup
maximize=true
